### ISSUE TITLE
GitHub Pagesデプロイ用のActionがPull Requestのpushで発火している疑惑がある

### ISSUE THREAD

**Issue by mitsuyoshi-yamazaki** [mitsuyoshi-yamazaki/mitsuyoshi-yamazaki.github.io#5]
```yaml
on:
  push:
    branches:
      - master  # Set a branch to deploy
  pull_request: <- こいつでは？
```
